FROM maven:3.8.3-openjdk-17

# FROM ubuntu:22.04
# RUN apt update
# RUN apt install openjdk-17-jdk -y
# RUN apt install maven

COPY . /opt/

WORKDIR /opt

COPY application.properties src/main/resources/application.properties

RUN mvn clean package

WORKDIR /opt/target/

EXPOSE 8080

ENTRYPOINT [ "java", "-jar" ]
CMD ["student-registration-backend.0.0.1-SNAPSHOT.jar"]



