apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  root-password: cm9vdF9wYXNzMTIz  # base64 encoded value of 'root_pass123'
  user-password: dXNlcl9wYXNzMTIz  # base64 encoded value of 'user_pass123'

