apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: backpod
      labels:
        app: back
    spec:
      containers:
        - name: backend
          image: ghcr.io/prasad3936/easyback:13572944a2fdb02911a9e94cf539879975e42d4b
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200M
            limits:
              cpu: 200m
              memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backpod
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: java
  
