apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: backpod
      labels:
        app: back
    spec:
      containers:
        - name: backend
          image: ghcr.io/prasad3936/easyback:c725e44e60b0be04ae7b57d208d59e1148e0970f
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200M
            limits:
              cpu: 200m
              memory: 500M
