apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sts
spec:
  selector:
    matchLabels:
      app: mydb
  serviceName: db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: myapp
          image: mariadb:latest
          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: student_db
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: mypvc

