apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sts
  labels:
    app: student-app-db
spec:
  selector:
    matchLabels:
      app: student-app-db
  serviceName: db-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: student-app-db
    spec:
      containers:
        - name: student-app-container
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-app-credentials
                  key: DB_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: student-app-credentials
                  key: DB_NAME
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: student-db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: student-db-volume
          persistentVolumeClaim:
            claimName: my-pvc
