apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  containers:
    - name: frontend-app
      image:
      ports:
        - containerPort: 80
  template:
    spec:
      containers:
        - image: ghcr.io/prasad3936/easyfront:2d4de1e0111ea149bda5beca01721cce09fc849e
