apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  containers:
    - name: frontend-app
      image:
      ports:
        - containerPort: 80
  template:
    spec:
      containers:
        - image: ghcr.io/prasad3936/easyfront:f7aa3a805b74aca056ceb2f92b88d18a1eeb1b93
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 80
  selector:
    app: frontend-app
  type: ClusterIP
  template:
    spec:
      containers:
        - image: ghcr.io/prasad3936/easyfront:f7aa3a805b74aca056ceb2f92b88d18a1eeb1b93
