apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  containers:
    - name: frontend-app
      image: 
      ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 80
  selector:
    app: frontend-app
  type: ClusterIP
