name: Build and Deploy to GHCR

on:
  push:
    branches:
      - kind
    # Trigger only if changes are outside /yaml/ and README.md files
    paths-ignore:
      - 'yaml/**'
      - '**/README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}
  RAW_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with lowercase name
        run: |
          IMAGE=$(echo "${RAW_IMAGE}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE ./backend

      - name: Push Docker image
        run: |
          docker push $IMAGE

  update-manifests:
    name: Update Kubernetes Manifests with Full Image Name
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Replace image name in manifests
        run: |
          find ./yaml -type f -name '*.yaml' -exec sed -i "s|image: .*|image: $IMAGE|g" {} \;

      - name: Commit updated manifests (excluding README files)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./yaml
          git reset README.md README.markdown README.txt || true
          git commit -m "Update image name to $IMAGE"
          git push
