name: Build and Deploy to GHCR

on:
  push:
    branches:
      - kind
    paths-ignore:
      - 'yaml/**'
      - '**/README.md'

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push Backend & Frontend Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          BACKEND_IMAGE=$(echo "${{ env.REGISTRY }}/${{ env.REPO }}-backend:${{ env.IMAGE_TAG }}" | tr '[:upper:]' '[:lower:]')
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
          docker build -t $BACKEND_IMAGE ./backend
          docker push $BACKEND_IMAGE

      - name: Build and Push Frontend Image
        run: |
          FRONTEND_IMAGE=$(echo "${{ env.REGISTRY }}/${{ env.REPO }}-frontend:${{ env.IMAGE_TAG }}" | tr '[:upper:]' '[:lower:]')
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV
          docker build -t $FRONTEND_IMAGE ./frontend
          docker push $FRONTEND_IMAGE

  update-manifests:
    name: Update Pod Manifests with Image Names
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Replace image name in backend-pod.yaml
        run: |
          sed -i "s|image: .*|image: $BACKEND_IMAGE|g" yaml/backend-pod.yaml

      - name: Replace image name in frontend-pod.yaml
        run: |
          sed -i "s|image: .*|image: $FRONTEND_IMAGE|g" yaml/frontend-pod.yaml

      - name: Commit updated manifests (excluding README files)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add yaml/backend-pod.yaml yaml/frontend-pod.yaml
          git commit -m "Update pod images to backend=$BACKEND_IMAGE and frontend=$FRONTEND_IMAGE"
          git push
